version: '3'

services:
  db:
    image: mongo:latest
    container_name: 'qna_db'
    restart: always
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mongo_volume:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    networks:
      - qna_backend

  app:
    container_name: 'qna_server'
    restart: always
    build: ./
    volumes:
      - .:/app
    ports:
      - 7000:7000
    depends_on:
      - db
    networks:
      - qna_backend

volumes:
  mongo_volume:

networks:
  qna_backend:
